// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L17Levels/L04.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture17",
  level: 4,
  name: "The Basel Problem",
  theoremName: "Lecture17_4",
  statement: "(a : ℕ → ℝ) (ha : ∀ n, a n = 1 / ((n + 2) ^ 2)) : SeriesConv a",
  introduction: `
# Level 4: The Basel Problem

Near the turn of the 18th century, the Bernoulli brothers Johann and Jakob became obsessed with evaluating the series:

\`∑ k, 1 / ((k + 2)²) = 1/4 + 1/9 + 1/16 + 1/25 + ...\`

This became known as the **Basel Problem** (after Basel, Switzerland, where the Bernoullis lived). Despite their considerable mathematical prowess, they could not find its exact value.

It would take several more decades, and their most brilliant student—the legendary Leonhard Euler—to solve it in 1734. Euler showed that:
$∑_{k=1}^\\infty 1/k^2 = \\pi^2/6$.

(Our series starts at k=2, so it equals \`π²/6 - 1\`, but that's a minor detail.)

## Our More Modest Goal

In this level, we won't compute the exact value—that requires Euler's revolutionary techniques connecting series to trigonometric functions. Instead, we'll prove something more fundamental: **the series converges at all**.

## The Strategy: Comparison

The key insight is to **compare** the Basel series with the Leibniz series from Levels 1-2. Observe that:
\`1/(k+2)² = 1/((k+2)(k+2)) ≤ 1/((k+1)(k+2))\`

Why? Because \`(k+2)² ≥ (k+1)(k+2)\` for all \`k ≥ 0\`.

By the Series Order Theorem (Level 3), this means:
\`∑_{k<n} 1/(k+2)² ≤ ∑_{k<n} 1/((k+1)(k+2)) = 1 - 1/(n+1) < 1\`

So the partial sums of the Basel series are **bounded above by 1**!

## New Theorems:

**New Theorem (\`SeqConv_of_IsCauchy\`):** The completeness of \`ℝ\` (which we proved).
If a sequence of **real** numbers is Cauchy, then it converges.
Recall that we had already proved that every Cauchy sequence in \`ℚ\` converges (\`Conv_of_IsCauchy\`)
to a real number. So why are we proving the same theorem again, just with real-valued sequences?
Couldn't we have stated and proved it once and for all for either type, \`a : ℕ → X\`?

No! The theorems are true for *completely different* reasons. \`Conv_of_IsCauchy\` is true
by the **construction** of the real numbers (as equivalence classes of Cauchy sequences of rationals).
Meanwhile, \`SeqConv_of_IsCauchy\` is true because of the **completeness** of the real numbers --
in fact, any "completion" of a metric space as equivalence classes of Cauchy sequences will
always be complete. Two different reasons / proofs, two different theorem statements.


**New Theorem (\`SeqConv_of_MonotoneBdd\`):** If a sequence \`a : ℕ → ℝ\` is:
- **Monotone:** \`a n ≤ a (n+1)\` for all \`n\`
- **Bounded:** \`a n ≤ M\` for all \`n\` and some \`M\`

We already proved that monotone bounded sequences are Cauchy (\`IsCauchy_of_MonotoneBdd\`). So
\`SeqConv_of_MonotoneBdd\` is simply combining
this with \`SeqConv_of_IsCauchy\`.

## Your Task

Prove that the Basel series converges by:

1. **First**, prove \`SeqConv_of_MonotoneBdd\` by combining \`IsCauchy_of_MonotoneBdd\` with completeness

2. **Then**, apply it to \`Series a\` where \`a n = 1/(n+2)²\`, showing:
   - The partial sums are **bounded** by 1 (using comparison with Leibniz series)
   - The partial sums are **monotone** (adding positive terms)

**Hints:**
- Use \`LeibnizSeriesFinite\` to get the formula for the Leibniz partial sums
- Use \`SeriesOrderThm\` to compare Basel with Leibniz
- Use \`Monotone_of_succ\` to prove monotonicity
- The inequality \`(k+2)² ≥ (k+1)(k+2)\` can be handled with \`field_simp\` and \`bound\`

This is a substantial proof—you're standing on the shoulders of giants!
`,
  conclusion: `
Magnificent! You've proven that the Basel series converges—a major milestone in the history of mathematics!

## What You've Accomplished

**Theorem:** The series \`∑ k, 1/(k+2)² = 1/4 + 1/9 + 1/16 + ...\` converges.

You proved this using the **Monotone Bounded Convergence Theorem**, which you first established by connecting two powerful results:
- \`IsCauchy_of_MonotoneBdd\`: monotone bounded sequences are Cauchy
- \`Conv_of_IsCauchy\`: by completeness of ℝ, Cauchy sequences converge

## The Proof Strategy

Your proof had three elegant components:

1. **Comparison with Leibniz:** You showed \`1/(k+2)² ≤ 1/((k+1)(k+2))\`, so by \`SeriesOrderThm\`, the Basel partial sums are bounded by the Leibniz partial sums, which equal \`1 - 1/(n+1) < 1\`.

2. **Boundedness:** The Basel series has partial sums bounded above by 1.

3. **Monotonicity:** Since each term \`1/(k+2)² > 0\`, the partial sums form a monotone increasing sequence.

Monotone + Bounded = Convergent! This is one of the fundamental patterns in real analysis.

## What We Haven't Shown

Notice that we've proven convergence but **not** computed the exact value! We know the series converges to *some* real number less than 1, but we don't know what it is.

Computing the exact value is much harder. Euler's brilliant solution in 1734 showed:
$\\sum_{k=1}^\\infty 1/k^2 = \\pi^2/6 \\approx 1.6449...$

See the homework problems for more details!

## The Broader Story: Riemann Zeta Function

Euler went on to evaluate \`∑ 1/k^(2n)\` for all positive integers \`n\`, showing each equals a rational multiple of \`π^(2n)\`. These are now known as special values of the **Riemann zeta function**:
\`ζ(s) = ∑_{k=1}^∞ 1/k^s\`

So \`ζ(2) = π²/6\`, \`ζ(4) = π⁴/90\`, \`ζ(6) = π⁶/945\`, etc.

But what about odd values? Is \`ζ(3) = ∑ 1/k³\` related to \`π\`, or any other known constant? This question is still open today! Only in 1978, did Roger Apéry manage to prove that \`ζ(3)\` is **irrational**! We do not have a **right** to mathematical knowledge; any time our ignorance is momentarily lifted, it is a cause for celebration.

## The Power of Comparison

Your proof demonstrated the **comparison test** in action: to prove a series converges, find a known convergent series that dominates it term-by-term. This is one of the most practical convergence tests in analysis.

## Historical Significance

The Basel Problem launched Euler's career and revolutionized the study of infinite series. It showed that series could encode deep connections between discrete sums and continuous quantities like \`π\`.

---

**Congratulations!** You've completed Lecture 17 and proven some of the most beautiful classical results about infinite series. You've mastered telescoping sums, the comparison test, and the monotone bounded convergence theorem—powerful tools you'll use throughout analysis.

**Next lecture:** We'll explore more sophisticated convergence tests and dive deeper into the theory of series!
`,
};

export default level;
