// AUTO-GENERATED by scripts/extract-commentary.mjs from
// vendor/RealAnalysisGame/Game/Levels/L25Levels/L01.lean
// Re-run the script to regenerate. Hand-edits will be overwritten.

import type { LevelSource } from '../../gameData';

const level: LevelSource = {
  world: "Lecture25",
  level: 1,
  name: "Uniform Convergence Implies Integrability",
  theoremName: "Lecture25_1",
  statement: `Integrable_of_UnifConv {f : ℕ → ℝ → ℝ} {F : ℝ → ℝ}
    {a b : ℝ} (hab : a < b)
    {ℓ : ℕ → ℝ}
    (hfint : ∀ n, HasIntegral (f n) a b (ℓ n))
    (hfF : UnifConv f F) :
    ∃ (L : ℝ), SeqLim ℓ L ∧ HasIntegral F a b L`,
  introduction: `
# Level 1: Uniform Convergence Implies Integrability

We finally prove the fundamental theorem that justifies Newton's bold term-by-term integration of infinite series! If a sequence of integrable functions \`fₙ\` converges uniformly to \`F\`, then \`F\` is also integrable, and crucially:

$$\\int F = \\lim (\\int fₙ)$$

or equivalently: $$\\int(\\lim fₙ) = \\lim (\\int fₙ)$$

This theorem is the rigorous foundation behind Newton's calculation from Lecture 2, where he integrated the binomial series term-by-term to compute π.

**Why uniform convergence?** As Socrates showed with his examples, pointwise convergence alone fails spectacularly:
- Step functions shifting to infinity: \`∫ fₙ = 1\` but \`∫(lim fₙ) = 0\`
- Spike functions on \`[0,1]\`: \`∫ fₙ = 1\` but \`∫(lim fₙ) = 0\`
- Even continuous tent functions: \`∫ fₙ = 1\` but \`∫(lim fₙ) = 0\`

The key insight is that uniform convergence gives us simultaneous control over all function values. If \`|fₙ(x) - F(x)| < ε/(b-a)\` for all \`x\` and large \`n\`, then Riemann sum differences are bounded by \`ε\`, allowing us to interchange limits and integrals.

**Remarkable fact**: We assume *nothing* about continuity! Integrability is strictly weaker than continuity, yet suffices for this profound result.

This theorem bridges the gap between finite and infinite processes, making rigorous what Newton intuited centuries ago.
`,
  conclusion: `
**Victory!** You've just proven one of the most important theorems in real analysis. This result:

- **Validates Newton's genius**: His term-by-term integration of power series, done purely by intuition in the 1660s, now has rigorous justification
- **Bridges finite and infinite**: Extends the linearity of integrals from finite sums to infinite series (under uniform convergence)
- **Enables modern analysis**: Makes possible the rigorous treatment of Fourier series, differential equations with series solutions, and much of mathematical physics

The proof strategy you used—controlling Riemann sum differences via uniform convergence—is a masterclass in how sophisticated mathematical concepts work together. You leveraged:
- The completeness of ℝ (Cauchy sequences converge)
- The definition of integrability (Riemann sums)
- Uniform convergence (simultaneous control over all function values)

**Historical note**: This theorem wasn't rigorously proven until the late 1800s, over 200 years after Newton used it! Mathematicians like Weierstrass, Riemann, and others had to develop the very foundations of real analysis to make Newton's intuitive leaps rigorous.

You've now mastered the deep connection between limits and integrals. In Level 2, we'll use all the machinery we've built to prove the most 'obvious' theorem in mathematics—one so intuitive that it was assumed without proof for over 2000 years!
`,
};

export default level;
